server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          confidential-client:
            provider: my-auth-server
            client-id: confidential-client
            client-secret: secret
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope: openid, profile, contacts.read, contacts.write
            redirect-uri: http://client.local:8080/login/oauth2/code/confidential-client
        provider:
          my-auth-server:
            issuer-uri: http://auth.local:9000

